### ISSUE TITLE
Buttons don't do anything

### ISSUE THREAD

**Issue by jgillich** [rexxars/sanity-plugin-markdown#1]
Just tried this plugin with Sanity 0.144.1: It is displayed and the preview works fine, but most of the buttons on the top don't do anything when clicked.

The "insert link" button opens a popup to enter the link, but then it doesn't actually add it to the text.

The buttons for header/bold/italic/quote don't do anything whatsoever.

**Comment by youvalv** [comment]
> The buttons for header/bold/italic/quote don't do anything whatsoever.

Tried it on FF - this issue reproduced.
Works as expected on Chrome

**Comment by rexxars** [comment]
Closing this as the repo has been moved to the official Sanity.io GitHub organization. 
The plugin has also been updated to a v2 with more features - feel free to try it out and if it's still an issue, open a new issue on the [new repository](https://github.com/sanity-io/sanity-plugin-markdown).
