### ISSUE TITLE
Im trying to add image in markdown from my machine but did not get any option for uploading local image as there is no upload option.It is just giving option for external URL..is there anyway for doing so?

### ISSUE THREAD

**Issue by ArslanHaideriintellect** [rexxars/sanity-plugin-markdown#2]

**Comment by adamsoffer** [comment]
+1

**Comment by nfwyst** [comment]
this is too bad....

**Comment by rexxars** [comment]
Closing this as the repo has been moved to the official Sanity.io GitHub organization. 
The plugin has also been updated to a v2 with more features - feel free to try it out and if it's still an issue, open a new issue on the [new repository](https://github.com/sanity-io/sanity-plugin-markdown).
