### ISSUE TITLE
possible to make the editor a bit wider?

### ISSUE THREAD

**Issue by iameli** [rexxars/sanity-plugin-markdown#3]
Hey, love the plugin. I'm new to Sanity. Is there any way to make the editor a bit wider? It would be cool if it could expand to take up the full screen, like the Sanity portable text editor can.

![image](https://user-images.githubusercontent.com/257909/80052355-5822e500-84cf-11ea-878d-d49dea40e855.png)

**Comment by rexxars** [comment]
Closing this as the repo has been moved to the official Sanity.io GitHub organization. 
The plugin has also been updated to a v2 with more features - feel free to try it out and if it's still an issue, open a new issue on the [new repository](https://github.com/sanity-io/sanity-plugin-markdown).
