### ISSUE TITLE
Split pane - editors side by side cause errors

### ISSUE THREAD

**Issue by dorelljames** [rexxars/sanity-plugin-markdown#5]
![image (3)](https://user-images.githubusercontent.com/977413/92003028-1d7d6300-ed73-11ea-98f6-53c429e93494.png)

If you open at least two editors side by side, as you type, it types random characters on the other side and the current editor becomes unusable.

Happens on `markdown` type and not on `blockContent`. Thanks

**Comment by rexxars** [comment]
Closing this as the repo has been moved to the official Sanity.io GitHub organization. 
The plugin has also been updated to a v2 with more features - feel free to try it out and if it's still an issue, open a new issue on the [new repository](https://github.com/sanity-io/sanity-plugin-markdown).
